modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="world_expansion"
version="0.1.4"
displayName="World Expansion: Light and Dark"
displayURL="https://www.curseforge.com/minecraft/mc-mods/world-expansion-light-and-dark Or https://modrinth.com/mod/world-expansion"
logoFile="logo.png"
credits="Hrumer, Samuelchik, Max_D"
authors="HorizonExpand"
description="This mod upgraded vanilla biomes and adds new for a more interesting journey around the world!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.world_expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.world_expansion]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.world_expansion]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration