
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.horizonexpand.world_expansion.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;

import net.minecraft.world.level.levelgen.feature.Feature;

import net.horizonexpand.world_expansion.world.features.ores.TitaniumOreFeature;
import net.horizonexpand.world_expansion.world.features.ores.RawTitaniumBlockFeature;
import net.horizonexpand.world_expansion.world.features.ores.DeepslateTitaniumOreFeature;
import net.horizonexpand.world_expansion.world.features.YellowAstilbaFeatureFeature;
import net.horizonexpand.world_expansion.world.features.WaterLakeFieldFeature;
import net.horizonexpand.world_expansion.world.features.WaterLakeFeature;
import net.horizonexpand.world_expansion.world.features.TumbleweedFeatureFeature;
import net.horizonexpand.world_expansion.world.features.TigerAloeVeraFeatureFeature;
import net.horizonexpand.world_expansion.world.features.RaiderBaseInBaobabFeature;
import net.horizonexpand.world_expansion.world.features.PumpkinFieldFeature;
import net.horizonexpand.world_expansion.world.features.MudRuin1Feature;
import net.horizonexpand.world_expansion.world.features.MudRuin1DesertFeature;
import net.horizonexpand.world_expansion.world.features.MudRuin1BadlandFeature;
import net.horizonexpand.world_expansion.world.features.LittleShroomlightHalloweenFeatureFeature;
import net.horizonexpand.world_expansion.world.features.KabanytGenerationFeature;
import net.horizonexpand.world_expansion.world.features.JackLanternFieldFeature;
import net.horizonexpand.world_expansion.world.features.JackLanternFeature;
import net.horizonexpand.world_expansion.world.features.HalloweenOakScarecrow3Feature;
import net.horizonexpand.world_expansion.world.features.HalloweenOakScarecrow2Feature;
import net.horizonexpand.world_expansion.world.features.HalloweenOakScarecrow1Feature;
import net.horizonexpand.world_expansion.world.features.HalloweenOakScarecrow0Feature;
import net.horizonexpand.world_expansion.world.features.HalloweenForestWellFeature;
import net.horizonexpand.world_expansion.world.features.HalloweenDarkOakScarecrow3Feature;
import net.horizonexpand.world_expansion.world.features.HalloweenDarkOakScarecrow2Feature;
import net.horizonexpand.world_expansion.world.features.HalloweenDarkOakScarecrow1Feature;
import net.horizonexpand.world_expansion.world.features.HalloweenDarkOakScarecrow0Feature;
import net.horizonexpand.world_expansion.world.features.GravelsurfaceFeature;
import net.horizonexpand.world_expansion.world.features.GrassPathFeature;
import net.horizonexpand.world_expansion.world.features.Drybaobab2Feature;
import net.horizonexpand.world_expansion.world.features.Drybaobab1Feature;
import net.horizonexpand.world_expansion.world.features.DiedAcacia5Feature;
import net.horizonexpand.world_expansion.world.features.DiedAcacia4Feature;
import net.horizonexpand.world_expansion.world.features.DiedAcacia3Feature;
import net.horizonexpand.world_expansion.world.features.DiedAcacia2Feature;
import net.horizonexpand.world_expansion.world.features.DiedAcacia1Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak9Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak8Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak7Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak6Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak5Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak4Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak3Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak2Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak1Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak11Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak10Feature;
import net.horizonexpand.world_expansion.world.features.DarkOak0Feature;
import net.horizonexpand.world_expansion.world.features.CoarseDirtSurfaceFeature;
import net.horizonexpand.world_expansion.world.features.Baobab9Feature;
import net.horizonexpand.world_expansion.world.features.Baobab8Feature;
import net.horizonexpand.world_expansion.world.features.Baobab7Feature;
import net.horizonexpand.world_expansion.world.features.Baobab6Feature;
import net.horizonexpand.world_expansion.world.features.Baobab5Feature;
import net.horizonexpand.world_expansion.world.features.Baobab4Feature;
import net.horizonexpand.world_expansion.world.features.Baobab3Feature;
import net.horizonexpand.world_expansion.world.features.Baobab2Feature;
import net.horizonexpand.world_expansion.world.features.Baobab1Feature;
import net.horizonexpand.world_expansion.world.features.Baobab10Feature;
import net.horizonexpand.world_expansion.world.features.AstilbaMulticoloredFeatureFeature;
import net.horizonexpand.world_expansion.world.features.AstilbaFeatureFeature;
import net.horizonexpand.world_expansion.world.features.AloeVeraFeatureFeature;
import net.horizonexpand.world_expansion.WorldExpansionMod;

@Mod.EventBusSubscriber
public class WorldExpansionModFeatures {
	public static final DeferredRegister<Feature<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.FEATURES, WorldExpansionMod.MODID);
	public static final RegistryObject<Feature<?>> TITANIUM_ORE = REGISTRY.register("titanium_ore", TitaniumOreFeature::new);
	public static final RegistryObject<Feature<?>> DEEPSLATE_TITANIUM_ORE = REGISTRY.register("deepslate_titanium_ore", DeepslateTitaniumOreFeature::new);
	public static final RegistryObject<Feature<?>> RAW_TITANIUM_BLOCK = REGISTRY.register("raw_titanium_block", RawTitaniumBlockFeature::new);
	public static final RegistryObject<Feature<?>> BAOBAB1 = REGISTRY.register("baobab1", Baobab1Feature::new);
	public static final RegistryObject<Feature<?>> BAOBAB2 = REGISTRY.register("baobab2", Baobab2Feature::new);
	public static final RegistryObject<Feature<?>> BAOBAB3 = REGISTRY.register("baobab3", Baobab3Feature::new);
	public static final RegistryObject<Feature<?>> BAOBAB4 = REGISTRY.register("baobab4", Baobab4Feature::new);
	public static final RegistryObject<Feature<?>> BAOBAB5 = REGISTRY.register("baobab5", Baobab5Feature::new);
	public static final RegistryObject<Feature<?>> BAOBAB6 = REGISTRY.register("baobab6", Baobab6Feature::new);
	public static final RegistryObject<Feature<?>> BAOBAB7 = REGISTRY.register("baobab7", Baobab7Feature::new);
	public static final RegistryObject<Feature<?>> BAOBAB8 = REGISTRY.register("baobab8", Baobab8Feature::new);
	public static final RegistryObject<Feature<?>> DRY_BAOBAB1 = REGISTRY.register("dry_baobab1", Drybaobab1Feature::new);
	public static final RegistryObject<Feature<?>> DRY_BAOBAB2 = REGISTRY.register("dry_baobab2", Drybaobab2Feature::new);
	public static final RegistryObject<Feature<?>> MUD_RUIN1_SAVANNA = REGISTRY.register("mud_ruin1_savanna", MudRuin1Feature::new);
	public static final RegistryObject<Feature<?>> MUD_RUIN1_DESERT = REGISTRY.register("mud_ruin1_desert", MudRuin1DesertFeature::new);
	public static final RegistryObject<Feature<?>> MUD_RUIN1_BADLANDS = REGISTRY.register("mud_ruin1_badlands", MudRuin1BadlandFeature::new);
	public static final RegistryObject<Feature<?>> BAOBAB_9 = REGISTRY.register("baobab_9", Baobab9Feature::new);
	public static final RegistryObject<Feature<?>> BAOBAB_10 = REGISTRY.register("baobab_10", Baobab10Feature::new);
	public static final RegistryObject<Feature<?>> RAIDER_BASE_IN_BAOBAB = REGISTRY.register("raider_base_in_baobab", RaiderBaseInBaobabFeature::new);
	public static final RegistryObject<Feature<?>> DIED_ACACIA_1 = REGISTRY.register("died_acacia_1", DiedAcacia1Feature::new);
	public static final RegistryObject<Feature<?>> DIED_ACACIA_2 = REGISTRY.register("died_acacia_2", DiedAcacia2Feature::new);
	public static final RegistryObject<Feature<?>> DIED_ACACIA_3 = REGISTRY.register("died_acacia_3", DiedAcacia3Feature::new);
	public static final RegistryObject<Feature<?>> DIED_ACACIA_4 = REGISTRY.register("died_acacia_4", DiedAcacia4Feature::new);
	public static final RegistryObject<Feature<?>> DIED_ACACIA_5 = REGISTRY.register("died_acacia_5", DiedAcacia5Feature::new);
	public static final RegistryObject<Feature<?>> JACK_LANTERN = REGISTRY.register("jack_lantern", JackLanternFeature::new);
	public static final RegistryObject<Feature<?>> GRAVEL_SURFACE = REGISTRY.register("gravel_surface", GravelsurfaceFeature::new);
	public static final RegistryObject<Feature<?>> COARSE_DIRT_SURFACE = REGISTRY.register("coarse_dirt_surface", CoarseDirtSurfaceFeature::new);
	public static final RegistryObject<Feature<?>> WATER_LAKE = REGISTRY.register("water_lake", WaterLakeFeature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_FOREST_WELL = REGISTRY.register("halloween_forest_well", HalloweenForestWellFeature::new);
	public static final RegistryObject<Feature<?>> ASTILBA_FEATURE = REGISTRY.register("astilba_feature", AstilbaFeatureFeature::new);
	public static final RegistryObject<Feature<?>> ASTILBA_MULTICOLORED_FEATURE = REGISTRY.register("astilba_multicolored_feature", AstilbaMulticoloredFeatureFeature::new);
	public static final RegistryObject<Feature<?>> YELLOW_ASTILBA_FEATURE = REGISTRY.register("yellow_astilba_feature", YellowAstilbaFeatureFeature::new);
	public static final RegistryObject<Feature<?>> TUMBLEWEED_FEATURE = REGISTRY.register("tumbleweed_feature", TumbleweedFeatureFeature::new);
	public static final RegistryObject<Feature<?>> TIGER_ALOE_VERA_FEATURE = REGISTRY.register("tiger_aloe_vera_feature", TigerAloeVeraFeatureFeature::new);
	public static final RegistryObject<Feature<?>> ALOE_VERA_FEATURE = REGISTRY.register("aloe_vera_feature", AloeVeraFeatureFeature::new);
	public static final RegistryObject<Feature<?>> GRASS_PATH = REGISTRY.register("grass_path", GrassPathFeature::new);
	public static final RegistryObject<Feature<?>> JACK_LANTERN_FIELD = REGISTRY.register("jack_lantern_field", JackLanternFieldFeature::new);
	public static final RegistryObject<Feature<?>> WATER_LAKE_FIELD = REGISTRY.register("water_lake_field", WaterLakeFieldFeature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_OAK_SCARECROW_0 = REGISTRY.register("halloween_oak_scarecrow_0", HalloweenOakScarecrow0Feature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_OAK_SCARECROW_1 = REGISTRY.register("halloween_oak_scarecrow_1", HalloweenOakScarecrow1Feature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_OAK_SCARECROW_2 = REGISTRY.register("halloween_oak_scarecrow_2", HalloweenOakScarecrow2Feature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_OAK_SCARECROW_3 = REGISTRY.register("halloween_oak_scarecrow_3", HalloweenOakScarecrow3Feature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_DARK_OAK_SCARECROW_0 = REGISTRY.register("halloween_dark_oak_scarecrow_0", HalloweenDarkOakScarecrow0Feature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_DARK_OAK_SCARECROW_1 = REGISTRY.register("halloween_dark_oak_scarecrow_1", HalloweenDarkOakScarecrow1Feature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_DARK_OAK_SCARECROW_2 = REGISTRY.register("halloween_dark_oak_scarecrow_2", HalloweenDarkOakScarecrow2Feature::new);
	public static final RegistryObject<Feature<?>> HALLOWEEN_DARK_OAK_SCARECROW_3 = REGISTRY.register("halloween_dark_oak_scarecrow_3", HalloweenDarkOakScarecrow3Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_0 = REGISTRY.register("dark_oak_0", DarkOak0Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_1 = REGISTRY.register("dark_oak_1", DarkOak1Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_2 = REGISTRY.register("dark_oak_2", DarkOak2Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_3 = REGISTRY.register("dark_oak_3", DarkOak3Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_4 = REGISTRY.register("dark_oak_4", DarkOak4Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_5 = REGISTRY.register("dark_oak_5", DarkOak5Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_6 = REGISTRY.register("dark_oak_6", DarkOak6Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_7 = REGISTRY.register("dark_oak_7", DarkOak7Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_8 = REGISTRY.register("dark_oak_8", DarkOak8Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_9 = REGISTRY.register("dark_oak_9", DarkOak9Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_10 = REGISTRY.register("dark_oak_10", DarkOak10Feature::new);
	public static final RegistryObject<Feature<?>> DARK_OAK_11 = REGISTRY.register("dark_oak_11", DarkOak11Feature::new);
	public static final RegistryObject<Feature<?>> LITTLE_SHROOMLIGHT_HALLOWEEN_FEATURE = REGISTRY.register("little_shroomlight_halloween_feature", LittleShroomlightHalloweenFeatureFeature::new);
	public static final RegistryObject<Feature<?>> PUMPKIN_FIELD = REGISTRY.register("pumpkin_field", PumpkinFieldFeature::new);
	public static final RegistryObject<Feature<?>> KABANYT_GENERATION = REGISTRY.register("kabanyt_generation", KabanytGenerationFeature::new);
}
