
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.horizonexpand.world_expansion.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.horizonexpand.world_expansion.block.YellowAstilbaBlock;
import net.horizonexpand.world_expansion.block.WindometerBlock;
import net.horizonexpand.world_expansion.block.TumbleweedBlock;
import net.horizonexpand.world_expansion.block.TitaniumOreBlock;
import net.horizonexpand.world_expansion.block.TitaniumBlockBlock;
import net.horizonexpand.world_expansion.block.SuspiciousMudBlock;
import net.horizonexpand.world_expansion.block.StrippedbaobabwoodBlock;
import net.horizonexpand.world_expansion.block.StrippedbaobablogBlock;
import net.horizonexpand.world_expansion.block.RawTitaniumBlockBlock;
import net.horizonexpand.world_expansion.block.MysteriousDoorBlock;
import net.horizonexpand.world_expansion.block.MultiCraftingTableBlock;
import net.horizonexpand.world_expansion.block.LittleShroomlightBlock;
import net.horizonexpand.world_expansion.block.KabanytwallBlock;
import net.horizonexpand.world_expansion.block.KabanyttileswallBlock;
import net.horizonexpand.world_expansion.block.KabanyttilesstairsBlock;
import net.horizonexpand.world_expansion.block.KabanyttilesslabBlock;
import net.horizonexpand.world_expansion.block.KabanyttilesBlock;
import net.horizonexpand.world_expansion.block.KabanytstairsBlock;
import net.horizonexpand.world_expansion.block.KabanytslabBlock;
import net.horizonexpand.world_expansion.block.KabanytbrickswallBlock;
import net.horizonexpand.world_expansion.block.KabanytbricksstairsBlock;
import net.horizonexpand.world_expansion.block.KabanytbricksslabBlock;
import net.horizonexpand.world_expansion.block.KabanytbricksBlock;
import net.horizonexpand.world_expansion.block.KabanytTitaniumOreBlock;
import net.horizonexpand.world_expansion.block.KabanytRedstoneOreOnBlock;
import net.horizonexpand.world_expansion.block.KabanytRedstoneOreBlock;
import net.horizonexpand.world_expansion.block.KabanytLapisOreBlock;
import net.horizonexpand.world_expansion.block.KabanytIronOreBlock;
import net.horizonexpand.world_expansion.block.KabanytGoldOreBlock;
import net.horizonexpand.world_expansion.block.KabanytEmeraldOreBlock;
import net.horizonexpand.world_expansion.block.KabanytDiamondOreBlock;
import net.horizonexpand.world_expansion.block.KabanytCopperOreBlock;
import net.horizonexpand.world_expansion.block.KabanytCoalOreBlock;
import net.horizonexpand.world_expansion.block.KabanytBlock;
import net.horizonexpand.world_expansion.block.JudasFruitPlantBlock;
import net.horizonexpand.world_expansion.block.HayBlockStairsBlock;
import net.horizonexpand.world_expansion.block.HayBlockSlabBlock;
import net.horizonexpand.world_expansion.block.DeepslateTitaniumOreBlock;
import net.horizonexpand.world_expansion.block.CarvedkabanytBlock;
import net.horizonexpand.world_expansion.block.BottleWithMiniFirefliesBlock;
import net.horizonexpand.world_expansion.block.BottleBlock;
import net.horizonexpand.world_expansion.block.BaobabtrapdoorBlock;
import net.horizonexpand.world_expansion.block.BaobabdoorBlock;
import net.horizonexpand.world_expansion.block.BaobabWoodBlock;
import net.horizonexpand.world_expansion.block.BaobabStairsBlock;
import net.horizonexpand.world_expansion.block.BaobabSlabBlock;
import net.horizonexpand.world_expansion.block.BaobabSaplingBlock;
import net.horizonexpand.world_expansion.block.BaobabPressurePlateBlock;
import net.horizonexpand.world_expansion.block.BaobabPlanksBlock;
import net.horizonexpand.world_expansion.block.BaobabLogBlock;
import net.horizonexpand.world_expansion.block.BaobabLeavesBlock;
import net.horizonexpand.world_expansion.block.BaobabFenceGateBlock;
import net.horizonexpand.world_expansion.block.BaobabFenceBlock;
import net.horizonexpand.world_expansion.block.BaobabButtonBlock;
import net.horizonexpand.world_expansion.block.AstilbamulticoloredBlock;
import net.horizonexpand.world_expansion.block.AstilbaBlock;
import net.horizonexpand.world_expansion.block.AloeVeraTigerBlock;
import net.horizonexpand.world_expansion.block.AloeVeraBlock;
import net.horizonexpand.world_expansion.WorldExpansionMod;

public class WorldExpansionModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(WorldExpansionMod.MODID);
	public static final DeferredBlock<Block> BAOBAB_WOOD = REGISTRY.register("baobab_wood", BaobabWoodBlock::new);
	public static final DeferredBlock<Block> BAOBAB_LOG = REGISTRY.register("baobab_log", BaobabLogBlock::new);
	public static final DeferredBlock<Block> BAOBAB_PLANKS = REGISTRY.register("baobab_planks", BaobabPlanksBlock::new);
	public static final DeferredBlock<Block> BAOBAB_LEAVES = REGISTRY.register("baobab_leaves", BaobabLeavesBlock::new);
	public static final DeferredBlock<Block> BAOBAB_STAIRS = REGISTRY.register("baobab_stairs", BaobabStairsBlock::new);
	public static final DeferredBlock<Block> BAOBAB_SLAB = REGISTRY.register("baobab_slab", BaobabSlabBlock::new);
	public static final DeferredBlock<Block> BAOBAB_FENCE = REGISTRY.register("baobab_fence", BaobabFenceBlock::new);
	public static final DeferredBlock<Block> BAOBAB_FENCE_GATE = REGISTRY.register("baobab_fence_gate", BaobabFenceGateBlock::new);
	public static final DeferredBlock<Block> BAOBAB_PRESSURE_PLATE = REGISTRY.register("baobab_pressure_plate", BaobabPressurePlateBlock::new);
	public static final DeferredBlock<Block> BAOBAB_BUTTON = REGISTRY.register("baobab_button", BaobabButtonBlock::new);
	public static final DeferredBlock<Block> STRIPPED_BAOBAB_WOOD = REGISTRY.register("stripped_baobab_wood", StrippedbaobabwoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_BAOBAB_LOG = REGISTRY.register("stripped_baobab_log", StrippedbaobablogBlock::new);
	public static final DeferredBlock<Block> BAOBAB_TRAPDOOR = REGISTRY.register("baobab_trapdoor", BaobabtrapdoorBlock::new);
	public static final DeferredBlock<Block> ASTILBA_MULTICOLORED = REGISTRY.register("astilba_multicolored", AstilbamulticoloredBlock::new);
	public static final DeferredBlock<Block> BAOBAB_DOOR = REGISTRY.register("baobab_door", BaobabdoorBlock::new);
	public static final DeferredBlock<Block> KABANYT = REGISTRY.register("kabanyt", KabanytBlock::new);
	public static final DeferredBlock<Block> KABANYT_BRICKS = REGISTRY.register("kabanyt_bricks", KabanytbricksBlock::new);
	public static final DeferredBlock<Block> KABANYT_TILES = REGISTRY.register("kabanyt_tiles", KabanyttilesBlock::new);
	public static final DeferredBlock<Block> CARVED_KABANYT = REGISTRY.register("carved_kabanyt", CarvedkabanytBlock::new);
	public static final DeferredBlock<Block> KABANYT_STAIRS = REGISTRY.register("kabanyt_stairs", KabanytstairsBlock::new);
	public static final DeferredBlock<Block> KABANYT_SLAB = REGISTRY.register("kabanyt_slab", KabanytslabBlock::new);
	public static final DeferredBlock<Block> KABANYT_WALL = REGISTRY.register("kabanyt_wall", KabanytwallBlock::new);
	public static final DeferredBlock<Block> KABANYT_BRICKS_STAIRS = REGISTRY.register("kabanyt_bricks_stairs", KabanytbricksstairsBlock::new);
	public static final DeferredBlock<Block> KABANYT_BRICKS_SLAB = REGISTRY.register("kabanyt_bricks_slab", KabanytbricksslabBlock::new);
	public static final DeferredBlock<Block> KABANYT_BRICKS_WALL = REGISTRY.register("kabanyt_bricks_wall", KabanytbrickswallBlock::new);
	public static final DeferredBlock<Block> KABANYT_TILE_STAIRS = REGISTRY.register("kabanyt_tile_stairs", KabanyttilesstairsBlock::new);
	public static final DeferredBlock<Block> KABANYT_TILE_SLAB = REGISTRY.register("kabanyt_tile_slab", KabanyttilesslabBlock::new);
	public static final DeferredBlock<Block> KABANYT_TILE_WALL = REGISTRY.register("kabanyt_tile_wall", KabanyttileswallBlock::new);
	public static final DeferredBlock<Block> YELLOW_ASTILBA = REGISTRY.register("yellow_astilba", YellowAstilbaBlock::new);
	public static final DeferredBlock<Block> TIGER_ALOE_VERA = REGISTRY.register("tiger_aloe_vera", AloeVeraTigerBlock::new);
	public static final DeferredBlock<Block> TUMBLEWEED = REGISTRY.register("tumbleweed", TumbleweedBlock::new);
	public static final DeferredBlock<Block> SUSPICIOUS_MUD = REGISTRY.register("suspicious_mud", SuspiciousMudBlock::new);
	public static final DeferredBlock<Block> ALOE_VERA = REGISTRY.register("aloe_vera", AloeVeraBlock::new);
	public static final DeferredBlock<Block> ASTILBA = REGISTRY.register("astilba", AstilbaBlock::new);
	public static final DeferredBlock<Block> LITTLE_SHROOMLIGHT = REGISTRY.register("little_shroomlight", LittleShroomlightBlock::new);
	public static final DeferredBlock<Block> TITANIUM_ORE = REGISTRY.register("titanium_ore", TitaniumOreBlock::new);
	public static final DeferredBlock<Block> TITANIUM_BLOCK = REGISTRY.register("titanium_block", TitaniumBlockBlock::new);
	public static final DeferredBlock<Block> RAW_TITANIUM_BLOCK = REGISTRY.register("raw_titanium_block", RawTitaniumBlockBlock::new);
	public static final DeferredBlock<Block> MULTI_CRAFTING_TABLE = REGISTRY.register("multi_crafting_table", MultiCraftingTableBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_TITANIUM_ORE = REGISTRY.register("deepslate_titanium_ore", DeepslateTitaniumOreBlock::new);
	public static final DeferredBlock<Block> BAOBAB_SAPLING = REGISTRY.register("baobab_sapling", BaobabSaplingBlock::new);
	public static final DeferredBlock<Block> KABANYT_COAL_ORE = REGISTRY.register("kabanyt_coal_ore", KabanytCoalOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_COPPER_ORE = REGISTRY.register("kabanyt_copper_ore", KabanytCopperOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_DIAMOND_ORE = REGISTRY.register("kabanyt_diamond_ore", KabanytDiamondOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_EMERALD_ORE = REGISTRY.register("kabanyt_emerald_ore", KabanytEmeraldOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_GOLD_ORE = REGISTRY.register("kabanyt_gold_ore", KabanytGoldOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_LAPIS_ORE = REGISTRY.register("kabanyt_lapis_ore", KabanytLapisOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_IRON_ORE = REGISTRY.register("kabanyt_iron_ore", KabanytIronOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_REDSTONE_ORE = REGISTRY.register("kabanyt_redstone_ore", KabanytRedstoneOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_TITANIUM_ORE = REGISTRY.register("kabanyt_titanium_ore", KabanytTitaniumOreBlock::new);
	public static final DeferredBlock<Block> KABANYT_REDSTONE_ORE_ON = REGISTRY.register("kabanyt_redstone_ore_on", KabanytRedstoneOreOnBlock::new);
	public static final DeferredBlock<Block> JUDAS_FRUIT_PLANT = REGISTRY.register("judas_fruit_plant", JudasFruitPlantBlock::new);
	public static final DeferredBlock<Block> WINDOMETER = REGISTRY.register("windometer", WindometerBlock::new);
	public static final DeferredBlock<Block> BOTTLE = REGISTRY.register("bottle", BottleBlock::new);
	public static final DeferredBlock<Block> BOTTLE_WITH_MINI_FIREFLIES = REGISTRY.register("bottle_with_mini_fireflies", BottleWithMiniFirefliesBlock::new);
	public static final DeferredBlock<Block> MYSTERIOUS_DOOR = REGISTRY.register("mysterious_door", MysteriousDoorBlock::new);
	public static final DeferredBlock<Block> HAY_BLOCK_STAIRS = REGISTRY.register("hay_block_stairs", HayBlockStairsBlock::new);
	public static final DeferredBlock<Block> HAY_BLOCK_SLAB = REGISTRY.register("hay_block_slab", HayBlockSlabBlock::new);
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
